### ISSUE TITLE
[xas_viewer] read Spec and ESRF BLISS HDF5 files via silx.io.open

### ISSUE THREAD

**Issue by maurov** [xraypy/xraylarch#281]
This issue is to keep track of the tasks required to get Spec and ESRF BLISS HDF5 files read by the `xas_viewer` GUI:

Improvements:
- [X] `read_specfile` (done in #277)
- [X] xas_viewer GUI reading single scan Spec files (#278 -> done in #282)
- [x] xas_viewer GUI reading multi-scan Spec files (#283)
- [x] add support for [BLISS](https://gitlab.esrf.fr/bliss/bliss)-type data files. (#289)

Bug fixing:
- [x] fix `DataSourceSpecH5().get_scan(scan=None)` -> take first scan by default at init (done in #285).
- [x] fix #286
- [x] fix #287
- [x] convert energy axis to eV for all imported groups at the data importer level (#288)
- [x] read spec files with misformat between scan header and file header (-> [fixed in silx](https://github.com/silx-kit/silx/issues/3459))
- [x] get default X array selection by `get_scan_axis` (#293 )
- [x] test for inconsistency in number of measurement points at `get_scan()` (as found out in #293 )

Maintenance:
- [x] remove `SpecfileData` and related functions or make them deprecated (is anybody using it?) (removed in #290)
- [x] remove redundant `scan=None` parameter in methods other than `set_scan()`

Documentation:
- [x] add an example in the documentation
