### ISSUE TITLE
coordinate release v0.9.58

### ISSUE THREAD

**Issue by maurov** [xraypy/xraylarch#337]
@newville seen the problems users are having with installing the `0.9.57` release with latest dependencies, I think it is good to release `0.9.58` by this week, what do you think?

I propose to complete the following list of tasks before release:

- [X] bug related to silx: #332 
- [X] bug related to numpy: #335
- [x] #333 (I will update the documentation soon)

Probably we should adopt semantic versioning for disentangling bug fixes from new features.

**Comment by newville** [comment]
@maurov yes, I think pushing out 0.9.58 as a "hot fix" for the silx/numpy issues should happen soon.  I hope to get that out by tomorrow but am also in "final push" of a funding proposal, so it might not happen until the weekend.

**Comment by maurov** [comment]
@newville I propose to wait the week-end, as I would like to push in the documentation the updated installation instructions for those who have already a Conda environment.

**Comment by newville** [comment]
@maurov it might be ok to separate code and doc, especially "release of docs".   But, this weekend is also unfortunately more realistic for me!
